### PR TITLE
Changed ConstantResultSubgraphTest instantiate

### PR DESCRIPTION
**Pull request by mandrono**
Issue: 49256

PR OV: https://github.com/openvinotoolkit/openvino/pull/4120

Links for internal validation in ticket

### CODE REVIEW

**Comment by mandrono** [comment]
@apankratovantonp @l-bat could you take a look please?

**Review by l-bat — APPROVED** [review]

**Review by apankratovantonp — APPROVED** [review]

**Review by l-bat — APPROVED** [review]

**Comment by alvoron** [comment]
@mandrono some tests were failed, could you please take a look?

**Comment by mandrono** [comment]
> @mandrono some tests were failed, could you please take a look?

As I can see there is no tests failed, only build failed but it is expected.
Please follow link in ticket comment to see actual validation results

**Comment by azhogov** [comment]
CI passed: https://gitlab-icv.inn.intel.com/inference-engine/product-configs/merge_requests/1371

**Pull request merged**
