### PR TITLE
[openvino-optimum] Add task specific examples

### PR DESCRIPTION
**Pull request by karkadad**
Adding a QA and text classification task specific examples which contains the following:
* A jupyter notebook containing an evaluation example
* A quantization example for NNCF accuracy aware training for a finetuned HF model for the question answering task

### CODE REVIEW

**Comment by alvoron** [comment]
@karkadad is it still valid?

**Comment by helena-intel** [comment]
> @karkadad is it still valid?

Yes, please do not close yet.

**Comment by alvoron** [comment]
Optimum module was removed from contrib: https://github.com/openvinotoolkit/openvino_contrib/pull/535
I assume we may close this PR now.

**Review by helena-intel — APPROVED** [review]

**Comment by helena-intel** [comment]
Not everything that is in this integration is supported in the optimum-intel integration in Hugging Face yet. I'm merging these examples to the 2022/3 branch so that they are not lost (the failing codestyle check can safely be ignored for this). Thanks very much for adding them @karkadad!

**Pull request merged**
