### PR TITLE
Give a unified name for ARM CPU plugin

### PR DESCRIPTION
**Pull request by ilya-lavrenov**

### CODE REVIEW

**Review by alvoron — APPROVED** [review]

**Comment by apankratovantonp** [comment]
May be rename `openvino_arm_cpu_plugin` ? @alvoron ?

**Comment by alvoron** [comment]
> May be rename `openvino_arm_cpu_plugin` ? @alvoron ?

agree.
@ilya-lavrenov  taking into account ARM GPU plugin could be added could you rename plugin to `openvino_arm_cpu_plugin`?

**Comment by ilya-lavrenov** [comment]
> > May be rename `openvino_arm_cpu_plugin` ? @alvoron ?
> 
> agree. @ilya-lavrenov taking into account ARM GPU plugin could be added could you rename plugin to `openvino_arm_cpu_plugin`?

updated, thanks

**Comment by alvoron** [comment]
@ilya-lavrenov 
just checked OV package, IE plugins have `libov` prefix, not `libopenvino`.
Sould you rename the plugin one more time? :)

**Pull request merged**
