### PR TITLE
Replace `interpreterFunction` with `interpret_model`

### PR DESCRIPTION
**Pull request by vurusovs**

### CODE REVIEW

**Comment by vurusovs** [comment]
build_jenkins

**Comment by ilya-lavrenov** [comment]
do we need to tests it via product config?

**Comment by vurusovs** [comment]
> do we need to tests it via product config?

For current state - yes, because there are conflicting changes. But we finally decided to replace `interpret*Function` with `TEMPLATE` plugin, so the will be no conflicts, and no need to check via `product-configs`

**Comment by vurusovs** [comment]
Implemented in scope of https://github.com/openvinotoolkit/openvino_contrib/pull/876

**Pull request closed without merging**
