### PR TITLE
[Tokenizers] Added LC_RPATH to additionally point to openvino's libs

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
Fixing https://dev.azure.com/openvinoci/dldt/_build/results?buildId=677156&view=logs&jobId=6c23757f-dbf6-510b-3bd6-0534daaa0edf&j=6c23757f-dbf6-510b-3bd6-0534daaa0edf&t=7d01fa6f-0d1f-5d8f-c395-ec4220521ec9

### CODE REVIEW

**Review by apaniukov — APPROVED** [review]

**Review by mryzhov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
azp run openvino_contrib-mac

**Pull request merged**
