### PR TITLE
Align SLT api with changes in OV.

### PR DESCRIPTION
**Pull request by sdurawa**
Align SLT api with changes in OV.

### CODE REVIEW

**Comment by sdurawa** [comment]
@apankratovantonp this PR requires only **approval**. It will be merged together with other 2 PRs (API change in OpenVINO and API update for ARM plugin).
There is a change in API for ConvolutionBackprop SLT (output_padding attribute and output_shape input were added [link](https://github.com/openvinotoolkit/openvino/blob/7c154058614470d3db0c905741b780cde9fc0953/inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/convolution_backprop_data.hpp)). With this PR I updated ConvolutionBackprop SLT for ARM plugin. I've also created a [pipeline](https://gitlab-icv.inn.intel.com/inference-engine/product-configs/pipelines/160746)with PRs to merge. All PRs will be merged when I will receive approval for them.

**Review by apankratovantonp — APPROVED** [review]

**Comment by alvoron** [comment]
@sdurawa is it targeted for 2021.4 release?

**Comment by sdurawa** [comment]
yes, this change is a part of 2021.4 release (https://jira.devtools.intel.com/browse/CVS-37430)

**Comment by alvoron** [comment]
@sdurawa  got it.

Next time, please, create a fork of the repository instead of pushing dev branch to the original repository.
Details are explained here: https://github.com/openvinotoolkit/openvino/wiki/Contribute

**Comment by alvoron** [comment]
@sdurawa please pull the latest changes from master - it should fix arm build on Azure.

**Comment by alvoron** [comment]
@sdurawa I've noticed CVS-37430 you referenced is already closed.
Should we merge this PR?

**Comment by sdurawa** [comment]
@alvoron, I converted ticket to draft as I will provide some changes next week into this PR. There is a new approach to resolve plugin [dependency](https://wiki.ith.intel.com/pages/viewpage.action?pageId=1663809825#nGraphOpsReferenceImplementations-HowtoresolveplugindependencyonIE/ngraphimplementationdetails(e.g.ngraph::runtime)) which won't break CI builds.

**Comment by sdurawa** [comment]
Closing this PR as the new one is created: https://github.com/openvinotoolkit/openvino_contrib/pull/161.

**Pull request closed without merging**
