### PR TITLE
[TOKENIZERS] Changed target name

### PR DESCRIPTION
**Pull request by mryzhov**
Updated target name to openvino_tokenizers

### CODE REVIEW

**Review by apaniukov — APPROVED** [review]

**Comment by apaniukov** [comment]
@dtrawins @jiwaszki we change target name from `user_ov_extensions` to `openvino_tokenizers`. It will require to update [MUSE example](https://github.com/openvinotoolkit/model_server/tree/main/demos/universal-sentence-encoder#start-the-model-server-in-a-container) and [docs](https://docs.openvino.ai/2023.2/ovms_demo_universal-sentence-encoder.html#start-the-model-server-in-a-container).

**Comment by dtrawins** [comment]
Does it have to be included in 2023.3 release? In OVMS RC image we are using the original lib name.  It is late to create new rc so in OVMS I would prefer to keep the current lib name.

**Comment by ilya-lavrenov** [comment]
> Does it have to be included in 2023.3 release? In OVMS RC image we are using the original lib name. It is late to create new rc so in OVMS I would prefer to keep the current lib name.

Ok, let's only fix package name, while library name will be changed in master (2024.0)

**Comment by slyalin** [comment]
> Does it have to be included in 2023.3 release? In OVMS RC image we are using the original lib name. It is late to create new rc so in OVMS I would prefer to keep the current lib name.

@dtrawins, are you redistributing the libraries with OVMS or use it as an extra dependency from the place that is affected by this PR?

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
