### PR TITLE
Backport of updates from release 2021.3 branch

### PR DESCRIPTION
**Pull request by terfendail**

### CODE REVIEW

**Comment by alvoron** [comment]
Could you please add [#76](https://github.com/openvinotoolkit/openvino_contrib/pull/76)?

**Review by dkurt — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@terfendail can we merge?

**Comment by dkurt** [comment]
> #69 added

@terfendail, seems like only https://github.com/openvinotoolkit/openvino_contrib/pull/63 but not https://github.com/openvinotoolkit/openvino_contrib/pull/69

**Comment by terfendail** [comment]
Added #69 and #76.

@ilya-lavrenov Wouldn't it be better to merge the branch after release to merge everything with a single PR? However if it's reasonable to merge it ASAP than PR is ready and I could remove draft state.

**Comment by ilya-lavrenov** [comment]
> Wouldn't it be better to merge the branch after release to merge everything with a single PR

I agree. Maybe it's even better to merge releases/2021/3 branch itlsef to master instead of manual cherry-pick..

**Comment by l-bat** [comment]
@alvoron  Should we add [#84](https://github.com/openvinotoolkit/openvino_contrib/pull/84)?

**Comment by alvoron** [comment]
> @alvoron Should we add [#84](https://github.com/openvinotoolkit/openvino_contrib/pull/84)?

Yes, we should. I think it would be easier to pick up all needed commits at the end as soon as 2020.3 is released.
Vitaly, it's up to you.

**Comment by terfendail** [comment]
I suppose we should wait till 2021.3 release tag creation, don't we?

**Comment by alvoron** [comment]
> I suppose we should wait till 2021.3 release tag creation, don't we?

Yes, I meant, you may pick up commits to your branch one by one (as you did previously) or do it once when tag is created.

**Comment by terfendail** [comment]
I've also added #93 that is later than 2021.3 tag

**Pull request merged**
